# -*- coding: utf-8 -*-
name             'marbase'
maintainer       'Martin Yrjölä'
maintainer_email 'martin.yrjola@gmail.com'
license          'CC'
description      'Installs/Configures marbase'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.16'

depends 'oh-my-zsh'
depends 'users'
depends 'chef-solo-search'
depends 'openssh'
depends 'apt'
depends 'build-essential'
depends 'git'
depends 'subversion'
depends 'mercurial'
depends 'pacman'
depends 'sudo'
depends 'python'
depends 'ssh_known_hosts'
depends 'fail2ban'
depends 'ufw'
depends 'logwatch'
depends 'rkhunter'
depends 'snort'
